### ISSUE TITLE
Not working on LibreWolf

### ISSUE THREAD

**Issue by katastrophe92** [raindropio/app#69]
Hello 👋. 

It does work on Firefox, didn't tried my Cromium browser yet. But LibreWolf is my daily driver ☹
First I logged in on the web GUI the I tried to sync the extension with the raindrop.io web but didn't let me.
Basic troubleshooting I did: close browser, restart PC

![librewolf 22-22-10 28March2023](https://user-images.githubusercontent.com/103950507/228359017-072f2200-c647-4b7e-959e-2c5757e7c960.gif)

**Comment by rokejulianlockhart** [comment]
Then isn't the problem caused by LibreWolf? If the upstream (and sole) extension target, `firefox`, is supported, this is caused by LibreWolf.

**Comment by rokejulianlockhart** [comment]
@katastrophe92, if you closed the issue because it was not reproducible on Firefox, then close the issue as invalid rather than https://github.com/raindropio/app/issues?q=is%3Aissue+is%3Aclosed+reason%3Acompleted. Additionally, you should open an issue at https://gitlab.com/groups/librewolf-community/-/issues.

If instead the issue was fixed, please clarify.
