### ISSUE TITLE
Read your browsing history

### ISSUE THREAD

**Issue by mukeshmithrakumar** [raindropio/app#77]
Any specific reason why I am getting a new permission grant request to `Read my browsing history` in Google Chrome

**Comment by naikmanish** [comment]
Greetings,
I am a paid subscriber and I do not want to give "Browsing History Access" by default.

You argue that all other bookmark managers have it by default. My argument, I use Raindrop because it did not have that requirement. 

It has to be optional and selectable. So if a user wants to save all pages, you can pop a message which says that you need to enable "Browsing History Access" and if a user needs that feature, he will enable it himself.

Please let me know via email if you are going to make it optional and when, so I can reinstall the extension in my browser. I dont want to give my browsing access history to raindrop by default. I dont know what you read and why you need it, but I dont want raindrop to read it.

At best, you can make it default for unpaid users, but for paid users I need that option please.

Thank you

**Comment by somegirl** [comment]
Ditto; I'm a paid subscriber and I like Raindrop a lot, but this is highly undesirable and I'll have to re-consider my subscription if this permission is going to stick. For now I'm leaving the extension disabled.

**Comment by exentrich** [comment]
Sorry for inconvenience. I decided to revert this change. No more "Browsing history" permission is asked in latest update.
Please go to Chrome Extensions settings and click "Update" to get latest update.

Why this happen? This permission have always been opt-in, and it required to work "Saved indicator", "Save all tabs" and "Highlights" feature. In my opinion those features are essential and should be enabled by default. That's why I decided to request this permission by default.

As history tells many users have complaint about this change. No problem to revert it back :)

**Comment by naikmanish** [comment]
Thank you for the quick and positive response ! 

I will reinstall the extension now. 

Thank you again for taking this positively and listening to your users. 

Good Luck

**Comment by somegirl** [comment]
Thank you!!
